kind:
  allowed:
    - operator
  required: true
  type: string
  meta:
    description: "Which service are you trying to use? Common kinds: `operator`, `job`"

version:
  allowed:
    - 1
  required: true
  type: number
  meta:
    description: "Operators may change yaml file schemas from version to version, as well as implementation details. Double check the version to ensure compatibility."

type:
  allowed:
    - forecast
  required: true
  type: string
  meta:
    description: "Type should always be `forecast` when using a forecast operator"

spec:
  required: false
  schema:
    historical_data:
      required: true
      type: dict
      meta:
        description: "This should be indexed by date and target category (optionally). It should include all targets and endogeneous data."
      schema:
        format:
          allowed:
            - csv
            - json
            - clipboard
            - excel
            - hdf
            - feather
            - load_files
          required: false
          type: string
        columns:
          required: false
          type: list
          schema:
            type: string
        options:
          nullable: true
          required: false
          type: dict
        url:
          required: false
          type: string
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/data.csv`"
        limit:
          required: false
          type: integer

    additional_data:
      required: false
      type: dict
      meta:
        description: "Additional datasets must be indexed by the same targets and target categories as the historical data. Also is must have datapoints for each date/category for your horizon. This must be exogeneous data."
      schema:
        format:
          allowed:
            - csv
            - json
            - clipboard
            - excel
            - hdf
            - feather
            - load_files
          required: false
          type: string
        columns:
          required: false
          type: list
          schema:
            type: string
        options:
          nullable: true
          required: false
          type: dict
        url:
          required: false
          type: string
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/data.csv`"
        limit:
          required: false
          type: integer

    test_data:
      required: false
      meta:
        description: "Optional, only if evaluation is needed."
      schema:
        connect_args:
          nullable: true
          required: false
          type: dict
        format:
          required: false
          type: string
          allowed:
            - csv
            - json
            - clipboard
            - excel
            - hdf
            - sql
        url:
          required: false
          type: string
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/data.csv`"
        name:
          required: false
          type: string
        options:
          nullable: true
          required: false
          type: dict
      type: dict

    output_directory:
      required: false
      schema:
        connect_args:
          nullable: true
          required: false
          type: dict
        format:
          required: false
          type: string
          allowed:
            - csv
            - json
            - clipboard
            - excel
            - hdf
            - sql
        url:
          required: false
          type: string
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/data.csv`"
        name:
          required: false
          type: string
        options:
          nullable: true
          required: false
          type: dict
      type: dict
    report_file_name:
      required: false
      type: string
      default: report.html
      meta:
        description: "Placed into output_directory location. Defaults to report.html"
    report_title:
      required: false
      type: string
    report_theme:
      required: false
      type: string
      default: light
      allowed:
        - light
        - dark
    report_metrics_name:
      required: false
      type: string
      default: report.csv
      meta:
        description: "Placed into output_directory location. Defaults to report.csv"

    target_column:
      type: string
      required: true

    datetime_column:
      type: dict
      required: true
      schema:
        name:
          type: string
          required: false
        format:
          type: string
          required: false

    target_category_columns:
      type: list
      required: false
      schema:
        type: string

    horizon:
      required: false
      schema:
        periods:
          type: integer
          required: false
        interval:
          type: integer
          required: false
        interval_unit:
          required: false
          type: string
          default: auto
          allowed:
            - S
            - M
            - H
            - D
            - W
            - Mo
            - Q
            - Y
      type: dict

    model:
      type: string
      required: false
      default: prophet
      allowed:
        - prophet
        - arima
        - neuralprophet
        - automlx

    model_kwargs:
      type: dict
      required: false

    confidence_interval_width:
      type: float
      required: false

    tuning:
      type: dict
      required: false
      schema:
        n_trials:
          type: integer
          required: false
          default: 10

    metric:
      type: string
      required: false
      default: MAPE
      allowed:
        - MAPE
        - RMSE
        - MSE
        - SMAPE
  type: dict
infrastructure:
  type: dict
  required: false
execution:
  type: dict
  required: false
